<a href="https://colab.research.google.com/github/grisliosc/MODUL_EDA_2/blob/main/HukPengWis_MODUL_EDA_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>





## LATIHAN 1

In [ ]:
import numpy as np

harga = np.array ([5000, 7000, 3000, 12000, 4500])
print('Rata-rata harga:', harga.mean())
print('Harga tertinggi:', harga.max())
print('Harga setelah diskon 10%:', harga * 0.9)

Rata-rata harga: 6300.0
Harga tertinggi: 12000
Harga setelah diskon 10%: [ 4500.  6300.  2700. 10800.  4050.]

**JAWABAN:**

Jika menggunakan list Python biasa, kode tersebut akan menghasilkan pesan error (TypeError). Python bawaan tidak bisa mengalikan list dengan bilangan desimal (float). Di Python standar, perkalian pada list hanya berfungsi dengan bilangan bulat (integer) untuk menggandakan/mengulang isi list (misal: [1, 2] * 2 menjadi [1, 2, 1, 2]). Sebaliknya, NumPy array memiliki fitur vectorization, yang memungkinkan operasi matematika diterapkan secara langsung ke setiap angka di dalam array tersebut sekaligus.

## LATIHAN 2

In [ ]:
import pandas as pd

data_kantin = {
    'menu': ['Nasi Goreng', 'Es Teh', 'Mie Ayam', 'Es Teh', None],
    'harga': [12000, 4000, 10000, 4000, 8000],
    'terjual': [23, 40, None, 35, 18]
}
df = pd.DataFrame(data_kantin)
print(df)

          menu  harga  terjual
0  Nasi Goreng  12000     23.0
1       Es Teh   4000     40.0
2     Mie Ayam  10000      NaN
3       Es Teh   4000     35.0
4         None   8000     18.0

**JAWABAN:**

Berdasarkan kode di modul, kolom yang memiliki data kosong (bernila None) adalah kolom menu dan terjual.

## LATIHAN 3

In [ ]:
import pandas as pd

df = pd.read_csv('data_kantin.csv')

df.head()

      tanggal         menu kategori  harga  terjual
0  2026-08-20   Teh Hangat  Minuman   3000     11.0
1  2026-08-31  Nasi Goreng  Makanan  12000     29.0
2  2026-08-21  Nasi Goreng  Makanan  12000     28.0
3  2026-08-28   Teh Hangat  Minuman   3000     12.0
4  2026-08-21     Es Jeruk  Minuman   5000     19.0

**JAWABAN:**

Kolom menu dan terjual akan memiliki angka non-null (data yang tidak kosong) lebih sedikit dari total baris. Artinya, di dalam kolom-kolom tersebut terdapat sel yang datanya hilang, kosong, atau tidak terisi (missing value).

In [ ]:
import pandas as pd

df = pd.read_csv('data_kantin.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   110 non-null    object
 1   menu      107 non-null    object
 2   kategori  110 non-null    object
 3   harga     110 non-null    int64
 4   terjual   104 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 4.4+ KB

In [ ]:
import pandas as pd

df = pd.read_csv('data_kantin.csv')

df.describe()

              harga     terjual
count    110.000000  104.000000
mean    6336.363636   22.923077
std     3520.001232   10.831178
min     2000.000000    8.000000
25%     3000.000000   13.000000
50%     5000.000000   20.000000
75%    10000.000000   33.000000
max    12000.000000   45.000000

In [ ]:
import pandas as pd

df = pd.read_csv('data_kantin.csv')

print(df.shape)

(110, 5)

## LATIHAN 4

In [ ]:
import pandas as pd

df = pd.read_csv('data_kantin.csv')

print(df.isnull().sum())
df['terjual'] = df['terjual'].fillna(0) # isi kekosongan dengan 0
df = df.dropna(subset=['menu']) # hapus baris jika kolom menu kosong

tanggal     0
menu        3
kategori    0
harga       0
terjual     6
dtype: int64

Ini adalah bagian dari logika pembersihan data (Data Cleaning):  

- Kolom terjual (Numerik): Jika jumlah terjual kosong, sangat logis untuk berasumsi bahwa pada saat itu barang tersebut tidak laku sama sekali, jadi masuk akal jika kita menggantinya dengan angka 0.
- Kolom menu (Kategorikal): Jika nama menu kosong, data tersebut kehilangan identitasnya. Kita tidak bisa menebak menu apa itu, dan baris data tanpa nama barang menjadi tidak berguna untuk dianalisis lebih lanjut (tidak bisa dikelompokkan). Oleh karena itu, baris tersebut lebih baik dibuang (drop).

## LATIHAN 5

In [ ]:
print(df.duplicated().sum()) # jumlah baris duplikat
df = df.drop_duplicates()

df['harga'] = df['harga'].astype(int) # memastikan tipe data harga adalah integer
print(df.dtypes)

5
tanggal      object
menu         object
kategori     object
harga         int64
terjual     float64
dtype: object

**JAWABAN:**

Memastikan tipe data benar sangat krusial karena komputer memproses data sesuai tipenya. Jika kolom harga secara tidak sengaja terbaca sebagai teks (string / object) alih-alih angka (integer), kamu tidak akan bisa menjumlahkan, mengalikan, atau mencari rata-ratanya. Fungsi astype(int) memastikan data tersebut diakui sebagai angka valid. Mengenai jumlah baris setelah drop_duplicates(), baris hanya akan berkurang jika ada dua baris (atau lebih) yang datanya sama persis dari ujung ke ujung.

## LATIHAN 6

In [ ]:
import pandas as pd

df = pd.read_csv('data_kantin.csv')

laris = df[df['terjual'] > 20]
urut = df.sort_values(by='terjual', ascending=False) # filtering

# sorting
df['total_pendapatan'] = df['harga'] * df['terjual'] # kolom turunan

ringkasan = df.groupby('menu')['total_pendapatan'].sum() # agregasi
print(ringkasan)

menu
Es Jeruk       1560000.0
Es Teh         2144000.0
Kerupuk        1042000.0
Mie Ayam       2570000.0
Nasi Goreng    4188000.0
Roti Bakar     1368000.0
Teh Hangat      459000.0
Name: total_pendapatan, dtype: float64


**JAWABAN:**

- Nasi Goreng: 12.000 * 23 = 276.000
- Es Teh: (4.000 * 40) + (4.000 * 35) = 300.000
- Mie Ayam: 10.000 * 0 (karena nilai kosong diganti 0) = 0
- Menu tertinggi adalah Es Teh (Rp 300.000).

Pengambilan Keputusan: Informasi ini membuktikan bahwa Es Teh adalah penyumbang pendapatan terbesar (produk paling laris). Kantin bisa mengambil keputusan untuk memperbanyak stok bahan pembuat Es Teh setiap harinya agar tidak kehabisan, atau membuat paket promo bundling (misal: Nasi Goreng + Es Teh) untuk mendongkrak penjualan makanan.

**## LATIHAN KELOMPOK**

**Nama Anggota:**
1. Dafi Alfarezel Rachman (08/ XI RPL 1)
2. Grisli Oscar Twi Billywanto (20/ XI RPL 1)

**Dataset Yang Dipilih:** Data kantin

**Pertanyaan Analisis Awal :**

1.   Menu apa yang paling banyak terjual dan menghasilkan pendapatan tertinggi?
2.   Kategori apa (Makanan/Minuman) yang paling diminati siswa?
3.   Bagaimana tren atau total pendapatan harian kantin?

**Dugaan Masalah Kualitas Data:**

1. Missing value pada kolom: menu (ada 3 data kosong) dan terjual (ada 6 data kosong).
2. Duplikat data: Ada 5 baris data yang ganda.
3. Tipe data tidak sesuai pada kolom: tanggal (masih berbentuk teks/
object, seharusnya datetime) dan terjual (berbentuk desimal/float, seharusnya bilangan bulat/integer).

**Rencana Teknik Pembersihan:**
1. Menghapus (drop) 5 baris data duplikat.
2. Menghapus baris yang kosong (dropna) pada kolom menu dan terjual, atau mengisi (imputasi) kolom terjual dengan nilai rata-rata (mean/median).
3. Mengubah tipe data kolom tanggal menjadi datetime dan terjual menjadi integer.

**Rencana Manipulasi Data:**

* Filter: Memilih data khusus untuk kategori 'Makanan' atau 'Minuman'.

* Sort: Mengurutkan data berdasarkan jumlah terjual terbanyak.

* Kolom turunan: Membuat kolom baru total_pendapatan (Rumus: harga * terjual).

* Groupby/agregasi: Mengelompokkan data berdasarkan menu lalu menjumlahkan (sum) kolom total_pendapatan.

**Jadwal Kerja:**

P3 (Loading & Inspection): Hari 1

P4 (Cleaning): Hari 1

P5 (Manipulation): Hari 2

P6 (Uji & Presentasi): Hari 3

**Pembagian Tugas Anggota:**

1. Dafi Alfarezel Rachman (08/ XI RPL 1) - Mencari Nilai Yang Anomali
2. Grisli Oscar Twi Billywanto (20/ XI RPL 1) - Melakukan Data Cleaning sebagai Antisipasi Kelalaian Database Awal.